name: Go
on: [push]
jobs:

  build:
    name: Build
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        
    - name: Install Ubuntu packages
      if: matrix.platform == 'ubuntu-latest'
      run: sudo apt update -y && sudo apt install -y libglfw3-dev

    - name: Build
      run:  mkdir dist && cd dist && go build ../cmd/client/ && go build -v ../cmd/server/
